### ISSUE TITLE
MP3 Audio too fast

### ISSUE THREAD

**Issue by TheAnton205** [sonydevworld/spresense-arduino-compatible#169]
**Description of the issue:** Hi, opened [this example for mp3 playing](Arduino15/packages/SPRESENSE/hardware/spresense/1.0.0/libraries/Audio/examples/application/player/player.ino) and everything works except for one thing: the audio seems to be playing too fast. When I upload the file, I get the message below in the serial monitor and the audio plays perfectly except it is like a sped up version of it. Changing the values for `usleep` does not change things, nor does adding `delay`.
```
initialization Audio Library
Open! 0x00000001
Play!
loop!!
Main player File End!
Main player error code: 5
```

**How to reproduce:** Open example, change `setVolume` from -160 to 120. Upload and that's all

**Describe your hardware setup:** Spresense main board on top of LTE expansion board. Speaker soldered to aux cord and plugged into headphone jack on expansion board. MP3s loaded from microSD. MP3s sounded normal speed when recorded.

**Software version used:** Arduino software 1.8.15. All libraries installed fresh today (6/20/22)

**Comment by SPRESENSE** [comment]
Hi @TheAnton205 san, 
Are you using the original player example(sketch) of arduino with your mp3 data file?
As you may know, the player has an auto sampling rate adjustable function but the channel number
using is fixed to two. This player is intended to use a stereo format data.
If you use a mp3 data recorded in monaural format, such a file is played in twice speed. Please
check if your data is a monaural one or not? If you would like to use a monaural data, could you
change the `AS_CHANNEL_STEREO` used as one of arguments of function at the following line to 
`AS_CHANNEL_MONO`?

https://github.com/sonydevworld/spresense-arduino-compatible/blob/master/Arduino15/packages/SPRESENSE/hardware/spresense/1.0.0/libraries/Audio/examples/application/player/player.ino#L89

Reference: 
https://developer.sony.com/develop/spresense/docs/arduino_tutorials_en.html#_program_description_2

**Comment by TheAnton205** [comment]
This solved it!! Thanks
