### ISSUE TITLE
Unable to install in Arduino IDE 2

### ISSUE THREAD

**Issue by maxgerhardt** [sonydevworld/spresense-arduino-compatible#230]
OS: Windows 10 x64
Arduino IDE: 2.3.2
Used package URL: 
```
https://raw.githubusercontent.com/sonydevworld/spresense-arduino-compatible/master/Arduino15/package_spresense_index.json
```
Error:
```
Downloading packages
SPRESENSE:spresense-sdk@1.0.0
SPRESENSE:spresense-tools@1.0.0
SPRESENSE:gcc-arm-none-eabi@9.2.1
SPRESENSE:spresense@1.0.0
Installing SPRESENSE:spresense-sdk@1.0.0
Failed to install platform: 'SPRESENSE:spresense:1.0.0'.
Error: 13 INTERNAL: Cannot install tool SPRESENSE:spresense-sdk@1.0.0: testing local archive integrity: testing archive size: fetched archive size differs from size specified in index: 26498276 != 6257789
```
So, the lines
https://github.com/sonydevworld/spresense-arduino-compatible/blob/5779633bf3b0ef38bc142cf900ee7f31240567ba/Arduino15/package_spresense_index.json#L52-L55
seems wrong is indeed `26498276 Bytes` big when downloading from that URL.

It installs just fine in the old Arduino IDE 1.8.19, but Arduino IDE 2 fails because of the wrong metadata in the package index.

Furthermore, the entries seem to be missing a `"checksum": "SHA-256:..."` entry.

**Comment by SPRESENSE** [comment]
Hi, maxgerhardt,

The URL you referenced should be changed to the correct one below.
https://github.com/sonydevworld/spresense-arduino-compatible/releases/download/generic/package_spresense_index.json

We are mentioning the URL on the following description.
https://developer.sony.com/spresense/development-guides/arduino_set_up_en.html#_installation_through_arduino_ide_board_manager

There are several versions to choose. the latest version of "Spresense Reference Board" on BOARDS MANAGER is 3.2.0.
Please change to the above URL and try to download.

Thanks

**Comment by maxgerhardt** [comment]
You're right, that package index looks much better; I picked the wrong one. Thanks!
