### ISSUE TITLE
Support for std libraries and c++14 / c++17

### ISSUE THREAD

**Issue by victorromeo** [sonydevworld/spresense-arduino-compatible#39]
Ubuntu 20.04 x64
Arduino IDE 1.8.13

Whilst attempting to compile the Arduino TensorFlowLite HelloWorld example, several errors are being observed.

There appear to be a number of std library functions which are currently not supported. The release of gcc-arm-none-eabi/5.4.1 is nearly 5 yrs old now, and the platform.txt specifies `-std=gnu++11` which is also an ageing standard now.  May I get advice how to modernise the toolchain to support these features?

A simple example of these failures can be seen by attempting to compile a simple sketch as below.
```c++
#include <cstdio>

void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}
```
Which derives the errors shown:
```
In file included from /home/xxxx/Arduino/SpresenseFault/SpresenseFault.ino:1:0:
/home/xxxx/.arduino15/packages/SPRESENSE/tools/gcc-arm-none-eabi/5.4.1/linux/arm-none-eabi/include/c++/5.4.1/cstdio:120:11: error: '::getc' has not been declared
   using ::getc;
           ^
/home/xxxx/.arduino15/packages/SPRESENSE/tools/gcc-arm-none-eabi/5.4.1/linux/arm-none-eabi/include/c++/5.4.1/cstdio:121:11: error: '::getchar' has not been declared
   using ::getchar;
           ^
/home/xxxx/.arduino15/packages/SPRESENSE/tools/gcc-arm-none-eabi/5.4.1/linux/arm-none-eabi/include/c++/5.4.1/cstdio:128:11: error: '::putc' has not been declared
   using ::putc;
           ^
/home/xxxx/.arduino15/packages/SPRESENSE/tools/gcc-arm-none-eabi/5.4.1/linux/arm-none-eabi/include/c++/5.4.1/cstdio:129:11: error: '::putchar' has not been declared
   using ::putchar;
           ^
/home/xxxx/.arduino15/packages/SPRESENSE/tools/gcc-arm-none-eabi/5.4.1/linux/arm-none-eabi/include/c++/5.4.1/cstdio:133:11: error: '::rewind' has not been declared
   using ::rewind;
           ^
/home/xxxx/.arduino15/packages/SPRESENSE/tools/gcc-arm-none-eabi/5.4.1/linux/arm-none-eabi/include/c++/5.4.1/cstdio:139:11: error: '::tmpfile' has not been declared
   using ::tmpfile;
           ^
exit status 1
Error compiling for board Spresense.
```

**Comment by takayoshi-k** [comment]
Hi, @victorromeo 

This is not a solution for your point but I tried to work the Tensorflow light micro HelloWorld on the spresense by using spresense sdk.
I think this can be alternative way for running TF Lite Micro HelloWorld on the spresense.

My work is on try_tensorflow_lm branch in <https://github.com/takayoshi-k/spresense.git>.

The following description is how to build it. (Note: This instructions are only tried in Ubuntu environment)

1. Install spresense sdk build environment on your ubuntu by following <https://developer.sony.com/develop/spresense/docs/sdk_set_up_en.html>
2. download a code and build it:
    $ git clone --recursive -b try_tensorflow_lm https://github.com/takayoshi-k/spresense.git
    $ cd spresense/examples/tf_helloworld
    $ ./install_libcxx.sh
    $ cd ../../sdk
    $ ./tools/config.py examples/tf_helloworld
    $ make
3. flash the built binary (nuttx.spk)
    $ ./tools/flash.sh -c <path to your ttyUSB device to the board> nuttx.spk

In the "make" execution, tensorflow code is downloaded into spresense/examples/tf_helloworld.

I hope this is an effective information for you.

**Comment by victorromeo** [comment]
Looks great thanks.
